{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Errors\n",
    "This simple notebook can be used list errors that happened while running various studies."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "%reload_ext autoreload\n",
    "%autoreload 2\n",
    "\n",
    "from IPython.core import ultratb\n",
    "\n",
    "ultratb.VerboseTB.tb_highlight = \"bg:#3e0054\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import os\n",
    "\n",
    "if not os.getcwd().endswith(\"syftr\"):\n",
    "    os.chdir(os.path.dirname(os.getcwd()))\n",
    "    print(f\"Changed working directory to: {os.getcwd()}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "\n",
    "from syftr.optuna_helper import get_study_names\n",
    "\n",
    "INCLUDE_REGEX = [\n",
    "    \".*llm2--thinking.*\",\n",
    "]\n",
    "EXCLUDE_REGEX = []\n",
    "\n",
    "study_names = get_study_names(\n",
    "    include_regex=INCLUDE_REGEX,\n",
    "    exclude_regex=EXCLUDE_REGEX,\n",
    ")\n",
    "\n",
    "pd.set_option(\"display.max_rows\", None)\n",
    "pd.set_option(\"display.max_columns\", None)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "from syftr.optuna_helper import get_failed_trials\n",
    "\n",
    "bad_trials = get_failed_trials(study_names=study_names)\n",
    "bad_trials"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "Traceback (most recent call last):\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/tuner/qa_tuner.py\", line 437, in objective\n",
    "    obj1, obj2, metrics, flow_json = evaluate(params, study_config)\n",
    "                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/tuner/qa_tuner.py\", line 128, in evaluate\n",
    "    obj1, obj2, results = _evaluate(params, study_config)\n",
    "                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/tuner/qa_tuner.py\", line 395, in _evaluate\n",
    "    results: T.Dict[str, T.Any] = eval_dataset(\n",
    "                                  ^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/evaluation/evaluation.py\", line 798, in eval_dataset\n",
    "    results, prune_reason = async_eval_debias(\n",
    "                            ^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/evaluation/evaluation.py\", line 657, in async_eval_debias\n",
    "    return _async_eval_runner(\n",
    "           ^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/evaluation/evaluation.py\", line 556, in _async_eval_runner\n",
    "    batch_result = loop.run_until_complete(\n",
    "                   ^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/nest_asyncio.py\", line 98, in run_until_complete\n",
    "    return f.result()\n",
    "           ^^^^^^^^^^\n",
    "  File \"/home/alex/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/lib/python3.12/asyncio/futures.py\", line 203, in result\n",
    "    raise self._exception.with_traceback(self._exception_tb)\n",
    "  File \"/home/alex/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n",
    "    result = coro.send(None)\n",
    "             ^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/evaluation/evaluation.py\", line 515, in _aeval_all_pair_runner\n",
    "    r = t.result()\n",
    "        ^^^^^^^^^^\n",
    "  File \"/home/alex/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/lib/python3.12/asyncio/futures.py\", line 203, in result\n",
    "    raise self._exception.with_traceback(self._exception_tb)\n",
    "  File \"/home/alex/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/lib/python3.12/asyncio/tasks.py\", line 314, in __step_run_and_handle_result\n",
    "    result = coro.send(None)\n",
    "             ^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/evaluation/evaluation.py\", line 430, in _aeval_pair_debias\n",
    "    response, run_time, call_data, generation_exception = await agenerate_pair(\n",
    "                                                          ^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py\", line 189, in async_wrapped\n",
    "    return await copy(fn, *args, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py\", line 111, in __call__\n",
    "    do = await self.iter(retry_state=retry_state)\n",
    "         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py\", line 153, in iter\n",
    "    result = await action(retry_state)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/tenacity/_utils.py\", line 99, in inner\n",
    "    return call(*args, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/tenacity/__init__.py\", line 418, in exc_check\n",
    "    raise retry_exc.reraise()\n",
    "          ^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/tenacity/__init__.py\", line 185, in reraise\n",
    "    raise self.last_attempt.result()\n",
    "          ^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/alex/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/lib/python3.12/concurrent/futures/_base.py\", line 449, in result\n",
    "    return self.__get_result()\n",
    "           ^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/home/alex/.local/share/uv/python/cpython-3.12.7-linux-x86_64-gnu/lib/python3.12/concurrent/futures/_base.py\", line 401, in __get_result\n",
    "    raise self._exception\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/tenacity/asyncio/__init__.py\", line 114, in __call__\n",
    "    result = await fn(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/evaluation/evaluation.py\", line 289, in agenerate_pair\n",
    "    return await exception_catcher(\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/evaluation/evaluation.py\", line 235, in exception_catcher\n",
    "    results = await func(**kwargs)\n",
    "              ^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/flows.py\", line 157, in agenerate\n",
    "    response, duration = await self._agenerate(query, invocation_id)\n",
    "                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/py_modules_files/_ray_pkg_83b6df9cbf7f7df4/syftr/flows.py\", line 491, in _agenerate\n",
    "    response: AgentChatResponse = await self.agent.achat(query)\n",
    "                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/callbacks/utils.py\", line 57, in async_wrapper\n",
    "    return await func(self, *args, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/agent/runner/base.py\", line 733, in achat\n",
    "    chat_response = await self._achat(\n",
    "                    ^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/agent/runner/base.py\", line 675, in _achat\n",
    "    cur_step_output = await self._arun_step(\n",
    "                      ^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/agent/runner/base.py\", line 477, in _arun_step\n",
    "    cur_step_output = await self.agent_worker.arun_step(step, task, **kwargs)\n",
    "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/callbacks/utils.py\", line 57, in async_wrapper\n",
    "    return await func(self, *args, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/agent/introspective/step.py\", line 209, in arun_step\n",
    "    reflective_agent_response = await reflective_agent.achat(original_response)\n",
    "                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/callbacks/utils.py\", line 57, in async_wrapper\n",
    "    return await func(self, *args, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/agent/runner/base.py\", line 733, in achat\n",
    "    chat_response = await self._achat(\n",
    "                    ^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/agent/runner/base.py\", line 675, in _achat\n",
    "    cur_step_output = await self._arun_step(\n",
    "                      ^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/agent/runner/base.py\", line 477, in _arun_step\n",
    "    cur_step_output = await self.agent_worker.arun_step(step, task, **kwargs)\n",
    "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/callbacks/utils.py\", line 57, in async_wrapper\n",
    "    return await func(self, *args, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/agent/introspective/reflective/tool_interactive_reflection.py\", line 384, in arun_step\n",
    "    correct_msg = await self._acorrect(\n",
    "                  ^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/agent/introspective/reflective/tool_interactive_reflection.py\", line 325, in _acorrect\n",
    "    correction = await self._correction_llm.astructured_predict(\n",
    "                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/llms/openai/base.py\", line 1069, in astructured_predict\n",
    "    return await super().astructured_predict(\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/llms/llm.py\", line 439, in astructured_predict\n",
    "    result = await program.acall(llm_kwargs=llm_kwargs, **prompt_args)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/program/function_program.py\", line 178, in acall\n",
    "    agent_response = await self._llm.apredict_and_call(\n",
    "                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/llms/function_calling.py\", line 294, in apredict_and_call\n",
    "    response = await self.achat_with_tools(\n",
    "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/llms/function_calling.py\", line 83, in achat_with_tools\n",
    "    response = await self.achat(**chat_kwargs)\n",
    "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/llms/openai_like/base.py\", line 204, in achat\n",
    "    return await super().achat(messages, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index_instrumentation/dispatcher.py\", line 368, in async_wrapper\n",
    "    result = await func(*args, **kwargs)\n",
    "             ^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/core/llms/callbacks.py\", line 76, in wrapped_async_llm_chat\n",
    "    f_return_val = await f(_self, messages, **kwargs)\n",
    "                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/llms/openai/base.py\", line 688, in achat\n",
    "    return await achat_fn(messages, **kwargs)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/llama_index/llms/openai/base.py\", line 743, in _achat\n",
    "    response = await aclient.chat.completions.create(\n",
    "               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/openai/resources/chat/completions/completions.py\", line 2589, in create\n",
    "    return await self._post(\n",
    "           ^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/openai/_base_client.py\", line 1794, in post\n",
    "    return await self.request(cast_to, opts, stream=stream, stream_cls=stream_cls)\n",
    "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n",
    "  File \"/tmp/ray/session_2025-08-18_15-43-19_812611_3475169/runtime_resources/pip/62bcbc7a32fb754587fea13cdeab3d02008a5798/virtualenv/lib/python3.12/site-packages/openai/_base_client.py\", line 1594, in request\n",
    "    raise self._make_status_error_from_response(err.response) from None\n",
    "openai.InternalServerError: Internal Server Error\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "syftr",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
